env:
  # Telegram
  TG_CHAT: "@Romdumprx"
  TG_TOKEN: ENCRYPTED[d1a9423df240b4603cb01c74226ce778d706ea74b0e392a648427279d2b1769c89ff6cb40d8d4010ac825ae2139258e4]
  
  # Gitlab
  PUSH_TO_GITLAB: true
  GITLAB_GROUP: RomdumprX

  GITLAB_TOKEN: ENCRYPTED[45935788bcd4fb135bab05e492e362f1e0e54c34d671564130d1a23cff80b58e31a77b62b04d4f55e6f0a5ceaed8e1ae]
  GITLAB_INSTANCE: www.opencode.net
  
  # Private SSH Key
  PRIV_SSH_KEY: ENCRYPTED[072ad4863d7705a64f1c898b4b4a1914de181e9fa12926d953db9595648f3df70ac4c9d0c822e1f90f31f482d93cacd7]

task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'RomdumprX'
  
  auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ubuntu-20.04

      privileged: true
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/neilchetty/Dumper-Scripts dumper
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa $GITLAB_INSTANCE >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "Sushrut1101"
      - git config --global user.email "guptasushrut@gmail.com"
      - cd dumper
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - echo "$GITLAB_INSTANCE" > .gitlab_instance
      - chmod a+x setup.sh
      - sudo bash setup.sh
     

  DumprX_script:
      - cd dumper || echo "Already in the Directory"
      - chmod a+x dumper.sh
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)
